---
kind: pipeline
type: docker
name: default-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: get-version
  image: debian:bullseye-slim
  commands:
    - "apt-get update && apt-get install curl jq"
    - "APPVERSION=$(curl https://api.github.com/repos/Wind4/vlmcsd/releases/latest | jq -r '.name' | cut -d'-' -f2)"
    - "echo $APPVERSION,latest > .tags"
- name: build
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: linutux/vlmcsd
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
  - main
  event:
  - push

---
kind: signature
hmac: 66b9b036d6e298c115b2bcd14d1f3cd86928ce68b2dc75d1b827f68422ca00ad

...
